### ISSUE TITLE
Password protection for static pages should use HTTPS

### ISSUE THREAD

**Issue by inspiredlabs** [matteobrusa/Password-protection-for-static-pages#13]
Browsers connecting via HTTP throw a security error and fail to display the green padlock. It might be worth specifying that on the docs/demo: https://matteobrusa.github.io/Password-protection-for-static-pages/

**Comment by matteobrusa** [comment]
Thanks for the suggestion, I've updated the readme. 
I'm still surprised of the popularity of this quick hack.
