### ISSUE TITLE
Question: does this work on GitHub pages?

### ISSUE THREAD

**Issue by textreme** [matteobrusa/Password-protection-for-static-pages#15]

**Comment by murillovp** [comment]
Also have interest in the answer.

**Comment by matteobrusa** [comment]
Aren't GitHub pages public by definition?

**Comment by murillovp** [comment]
Yes they are, even it being password protected someone could view the rep source code and even download it. But still, can it work?

**Comment by matteobrusa** [comment]
you might want to check the demo page linked in the read me.

**Comment by textreme** [comment]
ok so the answer is yes - thanks.

**Comment by rikrdo89** [comment]
What would be the best implementation for this in github pages? I want to use this to keep a directory password-protected (similar to what @matteobrusa did), but the "hash" folder will always be visible in the repository. How were you able to generate the demo to make the page public while keeping the "hash" folder hidden/private?
