### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by CSFlorin** [matteobrusa/Password-protection-for-static-pages#5]
Entered pw, made a folder with the name of the hash, then put new index in that folder but it still just says wrong pw.

**Comment by theofruitrouge** [comment]
Got the same issue.

**Comment by graphicsminded** [comment]
Same thing here. 
Environment: A sub-domain on a Godaddy.com cPanel shared-hosting account.

**Comment by matteobrusa** [comment]
What browser were you using? I'm trying to find a pattern.

**Comment by theofruitrouge** [comment]
Personally I used Firefox.

**Comment by graphicsminded** [comment]
Chrome Version 67.0.3396.99 (Official Build) (64-bit)

**Comment by matteobrusa** [comment]
I've added some troubleshooting hints to the readme.md, let me know if it helps.

**Comment by graphicsminded** [comment]
Typed in secret... You're hilarious!

**Comment by graphicsminded** [comment]
OK, followed directions, works great thanks. It's possible something didn't copy correctly before. I consider this solved.

Thanks again, great idea.
