### ISSUE TITLE
AWS S3 Security

### ISSUE THREAD

**Issue by apbreports** [matteobrusa/Password-protection-for-static-pages#6]
Hi Matteo,

You mentioned this as a solution on AWS S3. How could we ensure no search engines indexed the new folder or anyone was able to get the folder name another way? For example listing the directory.
I want to ensure no one had access to that new folder.
Thanks

**Comment by matteobrusa** [comment]
Folder listing is disabled by default on AWS. Just try it.

**Comment by apbreports** [comment]
I can't seem to list and directories so that is good news and I added a robots.txt to prevent search indexing. I was just afraid there was another way a person could list the directories with another tool (excluding browsers). I will keep and eye on the logs during the next weeks to see if there is any activity in that folder. Thanks

**Comment by matteobrusa** [comment]
I wouldn't rely on this approach for critical data, as brute force attack are hard to block. 
It was meant as a client-side only protection for the client-side only blogging platform https://github.com/matteobrusa/Tumbless
