### ISSUE TITLE
Tips for Internet Explorer?

### ISSUE THREAD

**Issue by conorfleming** [matteobrusa/Password-protection-for-static-pages#7]
This works really well in modern browsers, e.g. Chrome, Firefox and Edge. Do you have any tips for getting this to work in Internet Explorer? If I get it working I'll submit a pull request.

**Comment by matteobrusa** [comment]
I don't have any version of IE at hand, can you open the console and see where it hangs?

**Comment by Designnab** [comment]
Having the same problem in IE, it does not run the script to redirect into the launch page.

I got the login box to display by adding width: 100%;
	height: 100% to .box, but it still doesn't login only in IE:

.box {
	border-radius: 3px;
	background: rgba(101, 101, 101, 0.7); margin: auto; padding: 12px;
	width: 100%;
	height: 100%;
}
